#!/bin/bash
# Reconcile the systemd restart policy drop-in with process.restart values in
# configs/server.yaml.
#
# Reads process.restart.* from the operator config via load_server_config and
# renders ~/.config/systemd/user/paramem-server.service.d/restart.conf.
#
# Idempotent: if the drop-in already matches the desired content (byte-for-byte)
# neither the file nor daemon-reload is touched, avoiding churn on every start.
#
# Non-fatal: any failure (config unreadable, drop-in dir not writable, etc.)
# prints a Warning: line and exits 0 so server startup is not blocked.
#
# Runs automatically via start-server.sh after headless-boot.sh.

set -uo pipefail
cd "$(dirname "$0")/../.."

CONFIG="${PARAMEM_CONFIG:-configs/server.yaml}"
PYTHON="${PARAMEM_PYTHON:-python}"
DROPIN_DIR="${HOME}/.config/systemd/user/paramem-server.service.d"
DROPIN="${DROPIN_DIR}/restart.conf"

# ---------------------------------------------------------------------------
# Read restart policy fields from config via load_server_config.
# Emit shell-safe KEY=value lines to stdout; all other output goes to stderr.
# The 2>/dev/null suppresses logging noise (Env var ... not set) that
# load_server_config emits when optional API keys are absent.
# ---------------------------------------------------------------------------
if ! FIELDS=$(
    "$PYTHON" -c "
import sys
try:
    from paramem.server.config import load_server_config
    cfg = load_server_config('${CONFIG}')
    r = cfg.process.restart
    restart_val = 'on-failure' if r.on_failure else 'no'
    codes = ' '.join(str(c) for c in r.permanent_failure_exit_codes)
    # Shell-quote each value: the schema validators constrain the values
    # to numerics, the literal 'on-failure'/'no', and integers, but quoting
    # is cheap insurance against any future widening (e.g. a custom label).
    print(f'RESTART=\"{restart_val}\"')
    print(f'RESTART_SEC=\"{r.interval_seconds}\"')
    print(f'START_LIMIT_BURST=\"{r.max_attempts}\"')
    print(f'START_LIMIT_INTERVAL=\"{r.window_seconds}\"')
    print(f'PREVENT_EXIT_STATUS=\"{codes}\"')
except Exception as exc:
    sys.stderr.write(f'server-restart-reconcile: cannot read config: {exc}\n')
    sys.exit(1)
" 2>/dev/null
); then
    echo "  Warning: server-restart-reconcile: config read failed (check ${CONFIG})"
    exit 0
fi

# Evaluate the emitted assignments into the current shell.
eval "$FIELDS"

# ---------------------------------------------------------------------------
# Render the desired drop-in content.
# ---------------------------------------------------------------------------
DESIRED=$(cat <<EOF
# Auto-generated by scripts/setup/server-restart-reconcile.sh from configs/server.yaml.
# Do NOT edit by hand — re-run the reconciler.

[Unit]
StartLimitBurst=${START_LIMIT_BURST}
StartLimitIntervalSec=${START_LIMIT_INTERVAL}

[Service]
Restart=${RESTART}
RestartSec=${RESTART_SEC}
RestartPreventExitStatus=${PREVENT_EXIT_STATUS}
EOF
)

# ---------------------------------------------------------------------------
# Idempotency check: skip write + daemon-reload when already in sync.
# ---------------------------------------------------------------------------
if [ -f "${DROPIN}" ] && [ "$(<"${DROPIN}")" = "${DESIRED}" ]; then
    echo "  server-restart-reconcile: drop-in already up to date (${DROPIN})"
    exit 0
fi

# ---------------------------------------------------------------------------
# Atomic write: tmp in same dir + mv so readers never see a partial file.
# ---------------------------------------------------------------------------
if ! mkdir -p "${DROPIN_DIR}" 2>/dev/null; then
    echo "  Warning: server-restart-reconcile: cannot create ${DROPIN_DIR}"
    exit 0
fi

TMP=$(mktemp "${DROPIN_DIR}/.restart.conf.XXXXXX") || {
    echo "  Warning: server-restart-reconcile: cannot create temp file in ${DROPIN_DIR}"
    exit 0
}

printf '%s\n' "${DESIRED}" > "${TMP}" && mv "${TMP}" "${DROPIN}" || {
    rm -f "${TMP}"
    echo "  Warning: server-restart-reconcile: cannot write ${DROPIN}"
    exit 0
}

echo "  server-restart-reconcile: wrote ${DROPIN}"

# Reload so systemd picks up the new drop-in.  When daemon-reload fails,
# the on-disk drop-in and the running unit's view of restart policy
# diverge silently until the next host boot — flag the journalctl
# command so the operator can investigate without re-tracing the script.
if ! systemctl --user daemon-reload 2>/dev/null; then
    echo "  Warning: server-restart-reconcile: daemon-reload failed (non-fatal)"
    echo "           Running service uses the previous policy until next reload."
    echo "           Investigate: journalctl --user -u paramem-server.service -n 50"
fi
